version: '2'
services:
    contractcloud-app:
        image: contractcloud
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://contractcloud-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=contractcloud
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    contractcloud-mongodb:
        extends:
            file: mongodb.yml
            service: contractcloud-mongodb
